### ISSUE TITLE
Cookie Consent Popup Not Working As Intended

### ISSUE THREAD

**Issue by MikeFoden** [jhvanderschee/hugocodex#24]
Based on https://hugocodex.org/add-ons/cookie-consent/#manage-consent linking to the `main/layouts/partials/consent.html` file, I've noticed the following:

- Banner is displayed on every load even when `consent-settings` cookie is stored
- Script tags are being loaded even before 'Approve' is clicked
- When clicking 'Deny' it is not preventing any tags from being loaded.

I've tried this using the example provided (with a `ga.js` in my `static/js` folder) and it is loaded every time.

**Comment by Threnklyn** [comment]
hi, a cookie marked as `is_functional` always will be downloaded.

so using the example:
```yaml
items:
  - title: Google Anaytics (functional)
    description: This code gives us insight into the number of people that visit our website, where they are from and what they are clicking on.
    is_functional: true
    script_file: ga.js
  - title: Crisp chat
    description: This code gives users the option to chat directly with us through a chat box in the bottom right corner.
    is_functional: false
    script_file: crisp.js
```
will load `ga.js` but not `crisp.js`. `crisp.js` will only be loaded if approved.
So afaik it works as intended
